apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    prometheus: main
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
    - port: http
