apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-lb
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - name: service
      port: 3000
      protocol: TCP
  selector:
    app: grafana
