# This is a place holder for adding kubernetes external secrets, please add the
# ExternalSecret CR here, separated by `---`.
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: service-account             # The name of the Kubernetes Secret
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  projectId: k8s-infra-prow-build
  data:
  - key: prow-build-service-account # The name of the GSM Secret
    name: service-account.json      # The key to write to in the Kubernetes Secret
    version: latest                 # The version of the GSM Secret
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ssh-key-secret                          # The name of the Kubernetes Secret
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  projectId: k8s-infra-prow-build
  data:
  - key: prow-build-ssh-key-secret-ssh-public   # The name of the GSM Secret
    name: ssh-public                            # The key to write to in the Kubernetes Secret
    version: latest                             # The version of the GSM Secret
  - key: prow-build-ssh-key-secret-ssh-private  # The name of the GSM Secret
    name: ssh-private                           # The key to write to in the Kubernetes Secret
    version: latest                             # The version of the GSM Secret
