# This file is copy of octodns-config.yaml file except the gcp section under provider for the validation purpose.
# Update the octodns-config.yaml file likewise if any changes are made to this file.
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zone-configs
    enforce_order: false
    default_ttl: 3600

zones:
  # Canary targets.
  canary.kubernetes.io.:
    sources:
      - config
    targets:
      - gcp
  canary.k8s.io.:
    sources:
      - config
    targets:
      - gcp
  canary.k8s-e2e.com.:
    sources:
      - config
    targets:
      - gcp
  canary.x-k8s.io.:
    sources:
      - config
    targets:
      - gcp
  canary.k8s.dev.:
    sources:
      - config
    targets:
      - gcp
  canary.kubernetes.dev.:
    sources:
      - config
    targets:
      - gcp

  # Production targets.
  kubernetes.io.:
    sources:
      - config
    targets:
      - gcp
  k8s.io.:
    sources:
      - config
    targets:
      - gcp
  k8s-e2e.com.:
    sources:
      - config
    targets:
      - gcp
  x-k8s.io.:
    sources:
      - config
    targets:
      - gcp
  k8s.dev.:
    sources:
      - config
    targets:
      - gcp
  kubernetes.dev.:
    sources:
      - config
    targets:
      - gcp
