# permissions that are required beyond roles/owner to effectively manage
# our GCP organization, at least according to the role bindings that have
# been manually added to org admins thus far
title: Organization Admin
description: Access to administer all resources belonging to the organization
name: organization.admin
include:
  roles:
  - roles/billing.user
  - roles/resourcemanager.folderAdmin
  - roles/resourcemanager.organizationAdmin
  - roles/resourcemanager.projectCreator
