# allow listing of buckets
# TODO(https://github.com/kubernetes/k8s.io/issues/1659): remove once auditor.viewer is used instead
title: Storage Bucket Lister
description: Can list storage buckets
name: StorageBucketLister
include:
  roles:
  - roles/storage.admin
  permissionRegexes:
  - ^storage.buckets.
exclude:
  permissionRegexes:
  - create$
  - update$
  - delete$
  - IamPolicy$
