# google group for gcr.io/k8s-staging-networking is k8s-infra-staging-networking@kubernetes.io
registries:
- name: gcr.io/k8s-staging-networking
  src: true
- name: us.gcr.io/k8s-artifacts-prod/networking
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/networking
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/networking
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
