# This is a place holder for adding kubernetes external secrets, please add the
# ExternalSecret CR here, separated by `---`.
---
# Github Token synchronized from GCP Secrets Manager
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: k8s-infra-ci-robot-github-token
  namespace: prow
  labels:
    app: prow
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: k8s-infra-ci-robot-github-token # The name of the GSM Secret
    name: token                          # The key to write to in the Kubernetes Secret
    version: latest                      # The version of the GSM Secret
---
# Kubeconfigs of build clusters synchronized from GCP Secrets Manager
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: k8s-infra-build-clusters-kubeconfig
  namespace: prow
  labels:
    app: prow
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: k8s-infra-build-clusters-kubeconfig # The name of the GSM Secret
    name: kubeconfig                         # The key to write to in the Kubernetes Secret
    version: latest                          # The version of the GSM Secret
