apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: recaptcha             # The name of the Kubernetes Secret
  namespace: slack-infra
  labels:
    app: slackin
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: recaptcha-secret-key # The name of the GSM secret
    name: secret-key          # The key to write to in the Kubernetes Secret
    version: latest           # The version of the GSM secret
  - key: recaptcha-site-key   # The name of the GSM secret
    name: site-key            # The key to write to in the Kubernetes Secret
    version: latest           # The version of the GSM secret
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: slackin-token   # The name of the Kubernetes Secret
  namespace: slack-infra
  labels:
    app: slackin
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: slackin-token  # The name of the GSM secret
    name: token         # The key to write to in the Kubernetes Secret
    version: latest     # The version of the GSM secret
