kind: Service
apiVersion: v1
metadata:
  name: slackin2
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: slackin2
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
