# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
steps:
- name: gcr.io/cloud-builders/docker
  dir: .
  entrypoint: /usr/bin/make
  args:
    - build
    - TAG=$_TAG
    - TAG_DATE_SHA=$_GIT_TAG
substitutions:
  # variables set by kubernetes/test-infra/images/builder
  # set by image-builder to vYYYYMMDD-hash
  _GIT_TAG: "12345"
  _TAG: "latest"
images:
- "gcr.io/$PROJECT_ID/k8s-infra:$_GIT_TAG"
- "gcr.io/$PROJECT_ID/k8s-infra:$_TAG"