# google group for gcr.io/k8s-staging-test-infra is k8s-infra-staging-test-infra@kubernetes.io

registries:
- name: gcr.io/k8s-staging-test-infra
  src: true

# Promotes to the following GCR locations:
# - {us,eu,asia}.gcr.io/k8s-test-infra --> k8s.gcr.io
- name: us.gcr.io/k8s-test-infra
  service-account: k8s-infra-gcr-promoter@k8s-test-infra.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-test-infra
  service-account: k8s-infra-gcr-promoter@k8s-test-infra.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-test-infra
  service-account: k8s-infra-gcr-promoter@k8s-test-infra.iam.gserviceaccount.com
