apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: elekto-secret
  namespace: elekto
  labels:
    app: elekto
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: elekto-github-client-id
    name: GITHUB_CLIENT_ID
    version: latest
  - key: elekto-github-client-secret
    name: GITHUB_CLIENT_SECRET
    version: latest
  - key: elekto-db-username
    name: DB_USERNAME
    version: latest
  - key: elekto-db-password
    name: DB_PASSWORD
    version: latest
  - key: elekto-meta-secret
    name: META_SECRET
    version: latest
