# This is a place holder for adding kubernetes external secrets, please add the
# ExternalSecret CR here, separated by `---`.
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: cncf-ci-github-token
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  projectId: k8s-infra-prow-build-trusted
  data:
  - key: cncf-ci-github-token # The name of the GSM Secret
    name: token               # The key to write to in the Kubernetes Secret
    version: latest           # The version of the GSM Secret
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: snyk-token
  namespace: test-pods
spec:
  backendType: gcpSecretsManager
  data:
  - key: snyk-token   # The name of the GSM Secret
    name: SNYK_TOKEN  # The key to write to in the Kubernetes Secret
    version: latest   # The version of the GSM Secret
