# This is a place holder for adding kubernetes external secrets, please add the
# ExternalSecret CR here, separated by `---`.
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: k8s-infra-ci-robot-github-token
  namespace: prow
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: k8s-infra-ci-robot-github-token # The name of the GSM Secret
    name: token                          # The key to write to in the Kubernetes Secret
    version: latest                      # The version of the GSM Secret
