apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-packages
  labels:
    app: k8s-io-packages
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update kubernetes/k8s.io/apps/k8s-io-packages/README.md when you update this file
  nginx.conf: |
    worker_processes 5;

    events {
    }

    http {
      # Disable to show the nginx version
      server_tokens off;

      # This is the main site.
      server {
        listen 80 default_server;

        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
      }

      #
      # Vanity redirect rules.
      #

      # https://geko.cloud/en/forward-real-ip-to-a-nginx-behind-a-gcp-load-balancer/
      set_real_ip_from 2600:1901:0:95e7::; # LB IP
      set_real_ip_from 34.128.166.11/32; # LB IP
      set_real_ip_from 130.211.0.0/22; # IP SRC range for GCP Load Balancers
      set_real_ip_from 35.191.0.0/16; # IP SRC range for GCP Load Balancers
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;

      log_format json_combined escape=json
        '{'
          '"time":"$msec",'
          '"httpRequest":{'
            '"requestMethod":"$request_method",'
            '"requestUrl":"$scheme://$host$request_uri",'
            '"requestSize":$request_length,'
            '"status":"$status",'
            '"responseSize":$bytes_sent,'
            '"userAgent":"$http_user_agent",'
            '"remoteIp":"$remote_addr",'
            '"serverIp":"$server_addr",'
            '"referer":"$http_referer",'
            '"latency":"${request_time}s",'
            '"protocol":"$server_protocol"'
          '}'
        '}';

      access_log /dev/stdout json_combined;

      server {
        server_name legacy.apt.kubernetes.io legacy.apt.k8s.io;
        listen 80;

        rewrite ^/(.*)?$    https://packages.cloud.google.com/apt/$1 redirect;
      }

      server {
        server_name legacy.yum.kubernetes.io legacy.yum.k8s.io;
        listen 80;

        rewrite ^/(.*)?$    https://packages.cloud.google.com/yum/$1 redirect;
      }
    }
