apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-packages
  labels:
    app: k8s-io-packages
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update kubernetes/k8s.io/apps/k8s-io-packages/README.md when you update this file
  nginx.conf: |
    worker_processes 5;

    events {
    }

    http {
      # Disable to show the nginx version
      server_tokens off;

      # This is the main site.
      server {
        listen 80 default_server;

        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
      }

      #
      # Vanity redirect rules.
      #

      server {
        server_name legacy.apt.kubernetes.io legacy.apt.k8s.io;
        listen 80;

        rewrite ^/(.*)?$    https://packages.cloud.google.com/apt/$1 redirect;
      }

      server {
        server_name legacy.yum.kubernetes.io legacy.yum.k8s.io;
        listen 80;

        rewrite ^/(.*)?$    https://packages.cloud.google.com/yum/$1 redirect;
      }
    }
