# google group for gcr.io/k8s-staging-sig-docs k8s-infra-staging-sig-docs@kubernetes.io
registries:
  - name: gcr.io/k8s-staging-sig-docs
    src: true
  - name: us.gcr.io/k8s-artifacts-prod/sig-docs
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: eu.gcr.io/k8s-artifacts-prod/sig-docs
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
  - name: asia.gcr.io/k8s-artifacts-prod/sig-docs
    service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
